### ISSUE TITLE
install vscode angular2-snippets bug

### ISSUE THREAD

**Issue by skytriper** [johnpapa/vscode-angular-snippets#40] opened 2017-02-13 08:22 UTC
I install new vscode in 1.9.1 version and install "Angular TypeScript Snippets"  in Extensions View .
Reload is ok,but Extensions view always  show "reload" icon in the extension .it should be error.
 No show the reload icon is right.

 Btw install angular2 screen of lastest vscode and web install tutor guide  is different. No "Angular 2 TypeScript Snippets" item to select.

**Comment by tushar-chauhan** [comment] 2017-02-13 12:27
I cross verified this on VS Code version 1.9.1 on macOS Sierra.
The 'Reload' button is always visible, after this extension is updated to latest version.

**Comment by matteonovelli-zz** [comment] 2017-02-13 13:47
I have the same issue

**Comment by johnpapa** [comment] 2017-02-13 13:55
@chrisdias and I are looking into it

**Comment by chrisdias** [comment] 2017-02-13 14:12
Hi - It looks like you are running into [this issue in VS Code](https://github.com/Microsoft/vscode/issues/19685) which no longer repros in the [Insiders Builds](http://code.visualstudio.com/insiders).

Can folks try Insiders and if it still repros, please add a note to [19685](https://github.com/Microsoft/vscode/issues/19685) so we can get more scenarios and fix it in Feb?

Thanks, sorry for the glitch.

**Comment by shawnlan** [comment] 2017-02-13 18:10
Have the same issue after updating the extension from v1 to v2. Snippets still work though.

**Comment by chrisdias** [comment] 2017-02-13 18:12
@shawnlan are you running VS Code Insiders or Stable?

**Comment by shawnlan** [comment] 2017-02-13 18:13
Stable.

**Comment by chrisdias** [comment] 2017-02-13 18:15
this should be fixed in Insiders, if you get a chance to verify there that would be a big help. thanks!

**Comment by johnpapa** [comment] 2017-02-13 18:17
I just verified with @spboyer that it is happening for insiders too. // @chrisdias

**Comment by spboyer** [comment] 2017-02-13 18:20
Here is the screen shot after clicking "update" and "reload"

![johnpapa-angular2-snippets](https://cloud.githubusercontent.com/assets/7681382/22896715/204fc614-f1ef-11e6-81cb-b1bfd160d193.png)

**Comment by nahummor** [comment] 2017-02-13 19:14
I have the same issue on windows 10

**Comment by chrisdias** [comment] 2017-02-13 19:15
Windows or mac?

**Comment by chrisdias** [comment] 2017-02-13 19:16
Sorry I see mac 😀

**Comment by johnpapa** [comment] 2017-02-13 19:18
yes, @spboyer and I are on Macs. We have seen the behavior on both insiders and normal code.

I was able to get rid of the issue by uninstalling and reinstalling the extension. 

BTW - the issue is just annoying ... the extension still works.

**Comment by shawnlan** [comment] 2017-02-13 19:47
Both my Windows and Mac have this issue. Tried uninstalling and reinstalling. The version is updated, but the reload button is always there no matter what.

**Comment by KreativeKoder** [comment] 2017-02-13 20:33
It looked like it stoped working but I didn't catch the "Change prefix from ng2- to a- now that its just Angular".  All working good.  Looks like the reload button can just sit there all it wants now.

**Comment by skytriper** [comment] 2017-02-14 02:09
I updated to 2.0.1 version ,the view still show reload icon.
I work in windows 7 .

**Comment by dreamerleolioa** [comment] 2017-02-14 03:02
Reinstalling is okay, but the reload button always show.
And if click reload this extension will not work.

work on win 7 too.

**Comment by skytriper** [comment] 2017-02-14 05:28
update to 2.0.2 version ,it is still show reload icon.

**Comment by chrisdias** [comment] 2017-02-14 08:47
i reopened the issue in the vscode repo.

**Comment by kahamar** [comment] 2017-02-14 09:10
in package.json:
"name": "angular2" -> "name": "Angular2"

**Comment by rdzidziguri** [comment] 2017-02-14 12:38
@johnpapa Same here. installed 2.0.2 today but the issue remains.

**Comment by johnpapa** [comment] 2017-02-14 13:13
@chrisdias would #41 fix this?

**Comment by johnpapa** [comment] 2017-02-14 13:14
Try the new insiders build. It isnt happening for me now.

**Comment by johnpapa** [comment] 2017-02-14 13:30
Adding the link to the vscode issue https://github.com/Microsoft/vscode/issues/19685

**Comment by bman61** [comment] 2017-02-14 15:00
The folder name for the extension on my machine is johnpapa.Angular2-2.0.2
but the name in the package.json in that folder is angular2
When I changed the name in package.json to Angular2 (to match the case of the folder name) and restart vscode I don't see the reload button

**Comment by sandy081** [comment] 2017-02-14 16:26
@johnpapa Looks like the rename of extension name triggered this issue. Unfortunately, in the market place where the extensions are stored, re-name did not update the name. I suspect this started happening after you changed the name from `Angular2` -> `angular2`. 

To workaround temporarily, is it possible to revert it back to `Angular2` which might solve this reload/update issues which users are seeing and let us know if it worked. In the mean time, we will try to get this fixed from VS Code side and also in Market place. Sorry for it and thanks for the support.

**Comment by johnpapa** [comment] 2017-02-14 16:28
Yes, I can go back to Angular2. I wanted to use "Angular", but it wont allow it.


I just re-published 2.0.3 with the old name of `Angular2` ... try it please https://marketplace.visualstudio.com/items?itemName=johnpapa.Angular2

**Comment by matteonovelli-zz** [comment] 2017-02-14 17:03
v2.0.3 fixes the issue for me!

**Comment by nahummor** [comment] 2017-02-14 18:06
After update to 2.0.3 reload button disappears

**Comment by johnpapa** [comment] 2017-02-15 01:54
appears to be fixed in 2.0.3

problem was that the casing of the `package.json` name changed.

**Closed as completed by johnpapa** 2017-02-15 01:54 UTC

**Comment by rdzidziguri** [comment] 2017-02-15 14:17
@johnpapa I confirm this is fixed in 2.0.3
